import "dotenv/config";
import { chromium, expect as baseExpect } from "@playwright/test";

const expect = baseExpect.configure({ timeout: 15000 });
import { drizzle } from "drizzle-orm/node-postgres";
import { and, eq, inArray, like } from "drizzle-orm";
import { createHash, randomBytes, scryptSync } from "node:crypto";
import { mkdir } from "node:fs/promises";
import pg from "pg";
import { adminAccounts, adminRateLimits, adminSessions, bookings, catalogueImages, orders, products } from "../src/db/schema.ts";

const baseURL = process.env.TEST_BASE_URL ?? "http://127.0.0.1:3000";
const origin = new URL(baseURL).origin;
const prefix = `WHL-ADMIN-TEST-${randomBytes(6).toString("hex")}`;
const productName = `${prefix} Air Filter`;
const testEmail = `${prefix.toLowerCase()}@example.invalid`;
const testPassword = randomBytes(24).toString("base64url");
const hash = (value) => createHash("sha256").update(value).digest("hex");
const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL });
const db = drizzle(pool);
const browser = await chromium.launch({ headless: true, args: ["--no-sandbox"] });
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
const page = await context.newPage();
const publicContext = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
const visitor = await publicContext.newPage();
const errors = [];
for (const target of [page, visitor]) target.on("pageerror", (error) => errors.push(error.message));
const imageIds = [];
const [owner] = await db.select({ id: adminAccounts.id }).from(adminAccounts).where(eq(adminAccounts.id, "owner")).limit(1);
const testAdminId = owner ? prefix : "owner";
const rateEmail = `${prefix.toLowerCase()}-rate@example.invalid`;
await mkdir("artifacts", { recursive: true });
const post = (path, data, request = page.request) => request.post(`${baseURL}${path}`, { headers: { Origin: origin }, data });
const patch = (id, data) => page.request.patch(`${baseURL}/api/admin/products/${id}`, { headers: { Origin: origin }, data });
const rowFor = (name) => page.getByRole("row").filter({ has: page.getByRole("button", { name, exact: true }) });

try {
  const unauthenticated = await visitor.request.get(`${baseURL}/api/admin/products`);
  expect(unauthenticated.status()).toBe(401);
  expect((await post("/api/admin/products", {}, visitor.request)).status()).toBe(401);
  expect((await post("/api/admin/uploads", {}, visitor.request)).status()).toBe(401);
  expect((await visitor.request.patch(`${baseURL}/api/admin/products/ngk-spark-plug`, { headers: { Origin: origin }, data: { price: 1, version: 1 } })).status()).toBe(401);
  expect((await visitor.request.delete(`${baseURL}/api/admin/products/ngk-spark-plug`, { headers: { Origin: origin }, data: { version: 1 } })).status()).toBe(401);
  const loginHTML = await visitor.request.get(`${baseURL}/admin`);
  expect(loginHTML.headers()["x-frame-options"]).toBe("DENY");
  expect(loginHTML.headers()["x-robots-tag"]).toBe("noindex, nofollow");
  const html = await loginHTML.text();
  if (process.env.ADMIN_SETUP_KEY) expect(html.includes(process.env.ADMIN_SETUP_KEY)).toBe(false);
  console.log("PASS anonymous users cannot list, create, modify, delete or upload; private keys stay server-side");

  if (!owner) {
    expect(Boolean(process.env.ADMIN_SETUP_KEY)).toBe(true);
    const setupData = { name: "Test Shop Owner", email: testEmail, password: testPassword, confirmPassword: testPassword, setupKey: "invalid-setup-key" };
    expect((await post("/api/admin/setup", setupData)).status()).toBe(403);
    const crossOrigin = await page.request.post(`${baseURL}/api/admin/setup`, { headers: { Origin: "https://untrusted.invalid" }, data: { ...setupData, setupKey: process.env.ADMIN_SETUP_KEY } });
    expect(crossOrigin.status()).toBe(403);
    await page.goto(`${baseURL}/admin#setup=${process.env.ADMIN_SETUP_KEY}`);
    await expect(page.locator("input[name=setupKey]")).toHaveValue(/.+/);
    await expect(page).toHaveURL(`${baseURL}/admin`);
    await page.locator("input[name=name]").fill("Test Shop Owner");
    await page.locator("input[name=email]").fill(testEmail);
    await page.locator("input[name=password]").fill(testPassword);
    await page.locator("input[name=confirmPassword]").fill(testPassword);
    const setupResponse = page.waitForResponse((response) => response.url().endsWith("/api/admin/setup") && response.request().method() === "POST", { timeout: 60000 });
    await page.getByRole("button", { name: "Create owner account", exact: true }).click();
    expect((await setupResponse).status()).toBe(201);
    await expect(page.getByRole("heading", { name: /Catalogue & pricing/ })).toBeVisible({ timeout: 15000 });
    expect((await post("/api/admin/setup", { ...setupData, setupKey: process.env.ADMIN_SETUP_KEY }, visitor.request)).status()).toBe(409);
    console.log("PASS private owner setup, URL token removal and one-time enrollment protection");
  } else {
    const salt = randomBytes(24).toString("hex");
    const key = scryptSync(testPassword, salt, 64, { N: 32768, r: 8, p: 1, maxmem: 64 * 1024 * 1024 });
    await db.insert(adminAccounts).values({ id: testAdminId, name: "Test Shop Owner", email: testEmail, passwordHash: `scrypt$${salt}$${key.toString("hex")}` });
    expect((await post("/api/admin/login", { email: testEmail, password: testPassword })).status()).toBe(200);
    await page.goto(`${baseURL}/admin`);
    await expect(page.getByRole("heading", { name: /Catalogue & pricing/ })).toBeVisible();
    console.log("PASS isolated test-admin login; existing owner preserved");
  }

  const session = (await context.cookies()).find((cookie) => cookie.name === "whl-admin-session");
  expect(session.httpOnly).toBe(true);
  expect(session.sameSite).toBe("Strict");
  const [storedSession] = await db.select().from(adminSessions).where(eq(adminSessions.tokenHash, hash(session.value)));
  expect(storedSession.adminId).toBe(testAdminId);
  expect(storedSession.tokenHash).not.toBe(session.value);
  expect(await page.evaluate(() => document.cookie.includes("whl-admin-session"))).toBe(false);
  console.log("PASS HTTP-only sessions, server-side session hashes and authenticated dashboard");

  await page.waitForLoadState("networkidle");
  await page.screenshot({ path: "artifacts/admin-desktop.png", fullPage: true });
  await page.getByRole("button", { name: "Add product", exact: true }).click();
  let dialog = page.getByRole("dialog");
  await dialog.getByRole("textbox", { name: /Product name/ }).fill(productName);
  await dialog.getByRole("combobox", { name: /Category/ }).selectOption("engine");
  await dialog.getByRole("spinbutton").fill("28500");
  await dialog.getByRole("textbox", { name: /Description/ }).fill("Replacement air filter. Check motorcycle model and fitment before supply.");
  await dialog.getByRole("checkbox", { name: "Yamaha", exact: true }).check();
  await dialog.getByRole("checkbox", { name: "Kingboss", exact: true }).check();
  await dialog.getByRole("switch", { name: "Feature on the homepage", exact: true }).check();
  const uploadResponse = page.waitForResponse((response) => response.url().includes("/api/admin/uploads") && response.request().method() === "POST", { timeout: 60000 });
  await dialog.getByLabel("Upload product photo", { exact: true }).setInputFiles("public/images/engine-piston.png");
  const upload = await uploadResponse;
  expect(upload.status()).toBe(201);
  const uploadedImage = (await upload.json()).image;
  imageIds.push(uploadedImage.split("/").at(-1));
  await expect(dialog.getByText("Photo uploaded and ready to save.")).toBeVisible();
  await page.screenshot({ path: "artifacts/admin-editor-desktop.png", animations: "disabled" });
  const productResponse = page.waitForResponse((response) => response.url().endsWith("/api/admin/products") && response.request().method() === "POST", { timeout: 60000 });
  await dialog.getByRole("button", { name: "Add product", exact: true }).click();
  const productSave = await productResponse;
  expect(productSave.status(), JSON.stringify(await productSave.json())).toBe(201);
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await expect(rowFor(productName)).toBeVisible();
  const catalogue = await (await page.request.get(`${baseURL}/api/admin/products`)).json();
  const created = catalogue.products.find((product) => product.name === productName);
  expect(created.price).toBe(28500);
  expect(created.image).toBe(uploadedImage);
  const photo = await visitor.request.get(`${baseURL}${uploadedImage}`);
  expect(photo.status()).toBe(200);
  expect(photo.headers()["content-type"]).toBe("image/webp");
  await page.reload();
  await expect(rowFor(productName)).toBeVisible();
  await visitor.goto(`${baseURL}/shop?q=${encodeURIComponent(prefix)}`);
  await expect(visitor.locator(".product-card")).toHaveCount(1);
  await expect(visitor.locator(".product-price")).toHaveText("MK 28,500");
  await visitor.goto(baseURL);
  await expect(visitor.locator(".featured-section").getByRole("button", { name: productName, exact: true })).toBeVisible();
  console.log("PASS image upload, persistent product creation, correct shop pricing and featured homepage placement");

  const order = await post("/api/orders", { customerName: prefix, phone: "0888000005", fulfillment: "pickup", items: [{ productId: created.id, quantity: 2, price: 1 }], total: 2 }, visitor.request);
  expect(order.status()).toBe(201);
  const receipt = await order.json();
  expect(receipt.total).toBe(57000);
  await page.getByRole("button", { name: `Edit price for ${productName}`, exact: true }).click();
  dialog = page.getByRole("dialog");
  await dialog.getByRole("spinbutton", { name: "New price in Malawi kwacha", exact: true }).fill("31500");
  await dialog.getByRole("button", { name: "Update price", exact: true }).click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await expect(rowFor(productName).getByRole("button", { name: `Edit price for ${productName}`, exact: true })).toContainText("MK 31,500");
  await visitor.goto(`${baseURL}/shop?q=${encodeURIComponent(prefix)}`);
  await expect(visitor.locator(".product-price")).toHaveText("MK 31,500");
  const tracked = await (await post("/api/track", { reference: receipt.reference, phone: "0888000005" }, visitor.request)).json();
  expect(tracked.total).toBe(57000);
  expect(tracked.items[0].price).toBe(28500);
  const stale = await patch(created.id, { price: 1, version: created.version });
  expect(stale.status()).toBe(409);
  console.log("PASS quick price editing, storefront update, historical order preservation and stale-edit protection");

  let current = (await (await page.request.get(`${baseURL}/api/admin/products`)).json()).products.find((product) => product.id === created.id);
  for (const price of [-1, 0, 1.5, 10000001, "1000"]) expect((await patch(created.id, { price, version: current.version })).status()).toBe(400);
  expect((await patch(created.id, { image: "https://untrusted.invalid/photo.svg", version: current.version })).status()).toBe(400);
  const crossSite = await page.request.patch(`${baseURL}/api/admin/products/${created.id}`, { headers: { Origin: "https://untrusted.invalid" }, data: { price: 100, version: current.version } });
  expect(crossSite.status()).toBe(403);
  const svgUpload = await page.request.post(`${baseURL}/api/admin/uploads`, { headers: { Origin: origin }, multipart: { file: { name: "bad.svg", mimeType: "image/svg+xml", buffer: Buffer.from('<svg xmlns="http://www.w3.org/2000/svg"><script>alert(1)</script></svg>') } } });
  expect(svgUpload.status()).toBe(400);
  const fakePhoto = await page.request.post(`${baseURL}/api/admin/uploads`, { headers: { Origin: origin }, multipart: { file: { name: "fake.png", mimeType: "image/png", buffer: Buffer.from("not-an-image") } } });
  expect(fakePhoto.status()).toBe(400);
  console.log("PASS invalid prices, unsafe image references, invalid uploads and cross-origin requests are rejected");

  await page.getByRole("button", { name: `Edit ${productName}`, exact: true }).click();
  dialog = page.getByRole("dialog");
  await dialog.getByRole("textbox", { name: /Description/ }).fill("Updated fitment guidance from the owner. Please confirm your model before collection.");
  await dialog.getByRole("checkbox", { name: "Lifan", exact: true }).check();
  await dialog.getByRole("button", { name: "Save changes", exact: true }).click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  current = (await (await page.request.get(`${baseURL}/api/admin/products`)).json()).products.find((product) => product.id === created.id);
  expect(current.description).toContain("Updated fitment guidance");
  expect(current.compatibility).toContain("Lifan");
  await rowFor(productName).getByRole("switch").click();
  await expect(rowFor(productName).getByRole("switch")).toHaveAttribute("aria-checked", "false");
  await visitor.reload();
  await expect(visitor.locator(".product-card")).toHaveCount(0);
  expect((await post("/api/orders", { customerName: prefix, phone: "0888000005", fulfillment: "pickup", items: [{ productId: created.id, quantity: 1 }] }, visitor.request)).status()).toBe(400);
  await rowFor(productName).getByRole("switch").click();
  await expect(rowFor(productName).getByRole("switch")).toHaveAttribute("aria-checked", "true");
  console.log("PASS complete product editing, hiding, hidden-product order rejection and republishing");

  for (let index = 0; index < 3; index++) {
    const result = await post("/api/admin/products", { name: `${prefix} Hidden ${index + 1}`, category: "oils", price: 17500, description: "Temporary hidden catalogue test item.", compatibility: ["Yamaha"], image: "/images/engine-oil.png", active: false, featured: false });
    expect(result.status()).toBe(201);
  }
  await page.getByRole("button", { name: "Refresh catalogue", exact: true }).click();
  await expect(page.getByRole("button", { name: "Next products page", exact: true })).toBeEnabled();
  await page.getByRole("button", { name: "Next products page", exact: true }).click();
  await expect(page.locator(".admin-pagination>span")).toHaveText(/2 \/ /);
  await page.getByRole("button", { name: /^Hidden\d*/ }).click();
  await expect(page.locator(".admin-product-table tbody tr")).toHaveCount(3);
  await page.getByRole("textbox", { name: "Search admin catalogue" }).fill("not-a-real-part");
  await expect(page.getByRole("heading", { name: "No parts on this shelf." })).toBeVisible();
  await page.getByRole("button", { name: "Clear filters", exact: true }).first().click();
  await page.getByRole("combobox", { name: "Filter catalogue by category" }).selectOption("engine");
  await expect(page.locator(".admin-product-table tbody tr")).toHaveCount(2);
  await page.getByRole("combobox", { name: "Filter catalogue by category" }).selectOption("all");
  console.log("PASS hidden drafts, catalogue refresh, pagination, category filters and empty-state recovery");

  await page.setViewportSize({ width: 390, height: 844 });
  await page.waitForTimeout(250);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true);
  await page.screenshot({ path: "artifacts/admin-mobile.png", fullPage: true });
  await page.getByRole("textbox", { name: "Search admin catalogue" }).fill(productName);
  await page.getByRole("button", { name: `Edit ${productName}`, exact: true }).click();
  await expect(page.getByRole("dialog")).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true);
  await page.screenshot({ path: "artifacts/admin-editor-mobile.png" });
  await page.getByRole("button", { name: "Cancel", exact: true }).click();
  await page.getByRole("button", { name: `Delete ${productName}`, exact: true }).click();
  await page.getByRole("button", { name: "Keep product", exact: true }).click();
  await expect(rowFor(productName)).toBeVisible();
  await page.getByRole("button", { name: `Delete ${productName}`, exact: true }).click();
  await page.getByRole("button", { name: "Delete product", exact: true }).click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await expect(rowFor(productName)).toHaveCount(0);
  const existingOrder = await (await post("/api/track", { reference: receipt.reference, phone: "0888000005" }, visitor.request)).json();
  expect(existingOrder.total).toBe(57000);
  await visitor.reload();
  await expect(visitor.locator(".product-card")).toHaveCount(0);
  console.log("PASS mobile admin layout, product forms, deletion confirmation and retained historical orders");

  await page.getByRole("button", { name: "Sign out", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Welcome back." })).toBeVisible();
  expect((await page.request.get(`${baseURL}/api/admin/products`)).status()).toBe(401);
  await page.locator("input[name=email]").fill(testEmail);
  await page.locator("input[name=password]").fill("incorrect-password");
  await page.getByRole("button", { name: "Sign in to your shop", exact: true }).click();
  await expect(page.locator(".admin-auth-form").getByRole("alert")).toContainText("The email or password is incorrect.");
  await page.locator("input[name=password]").fill(testPassword);
  await page.getByRole("button", { name: "Sign in to your shop", exact: true }).click();
  await expect(page.getByRole("heading", { name: /Catalogue & pricing/ })).toBeVisible();
  await db.update(adminSessions).set({ expiresAt: new Date(Date.now() - 1000) }).where(eq(adminSessions.adminId, testAdminId));
  expect((await page.request.get(`${baseURL}/api/admin/products`)).status()).toBe(401);
  await page.reload();
  await expect(page.getByRole("heading", { name: "Welcome back." })).toBeVisible();
  for (let attempt = 1; attempt <= 11; attempt++) {
    const result = await post("/api/admin/login", { email: rateEmail, password: "wrong-password" }, visitor.request);
    expect(result.status()).toBe(attempt <= 10 ? 401 : 429);
  }
  expect(errors).toEqual([]);
  console.log("PASS logout revocation, incorrect-password handling, session expiry and login rate limiting");
  console.log("ALL ADMIN CATALOGUE AND SECURITY CHECKS PASSED");
} finally {
  await db.delete(orders).where(eq(orders.customerName, prefix));
  await db.delete(bookings).where(eq(bookings.customerName, prefix));
  await db.delete(products).where(like(products.name, `${prefix}%`));
  if (imageIds.length) await db.delete(catalogueImages).where(inArray(catalogueImages.id, imageIds));
  await db.delete(adminAccounts).where(and(eq(adminAccounts.id, testAdminId), eq(adminAccounts.email, testEmail)));
  const rateKeys = [`login-email:${hash(testEmail)}`, `login-email:${hash(rateEmail)}`, `image-upload:${testAdminId}`, ...(!owner ? ["owner-setup"] : [])];
  await db.delete(adminRateLimits).where(inArray(adminRateLimits.key, rateKeys));
  await pool.end();
  await browser.close();
  console.log("Temporary admin, catalogue images, products and test orders cleaned up. Existing owner and shop records preserved.");
}
